**NUMPY Module functions**

In [52]:
import numpy as np

In [16]:
array1 = np.array([1,2,3,4,5])
print(array1)
print(type(array1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
for i in range(len(array1)):
  print(array1[i])

1
2
3
4
5


In [6]:
sum = 0
for i in range(len(array1)):
  sum += array1[i]

print(sum)

15


In [7]:
#[start:end] --> start is inclusive where as end is exclusive
print(array1[2:4])

[3 4]


Below is a list of all data types in NumPy and the characters used to represent them.

*   i - integer
*   b - boolean
*   u - unsigned integer
*   f - float
*   c - complex float
*   m - timedelta
*   M - datetime
*   O - object
*   S - string
*   U - unicode string
*   V - fixed chunk of memory for other type ( void )




In [15]:
print(array1.dtype)

int32


Functions : 
*   COPY
*   VIEW

In [17]:

# --> COPY
x = array1.copy()
array1[0] = 69
print(array1)
print("****")
print(x)

[69  2  3  4  5]
****
[1 2 3 4 5]


In [18]:
# --> VIEW
x = array1.view()
array1[0] = 69
print(array1)
print("****")
print(x)

[69  2  3  4  5]
****
[69  2  3  4  5]


Shape of an Array

In [23]:
array2 = np.array([[1,2,3,4,5],[11,12,13,14,15]])
print(array2.shape)

print(array2)

array3 = np.array([1,2,3,4,5],ndmin = 5)
print(array3.shape)

(2, 5)
[[ 1  2  3  4  5]
 [11 12 13 14 15]]
(1, 1, 1, 1, 5)


Reshape of an array

In [27]:
array4 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newArray4 = array4.reshape(4,3)
print(newArray4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


1d to 3d array using reshape

In [28]:
array5 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newArray5 = array5.reshape(2,3,2)
print(newArray5)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


Accessing 3d array

In [31]:
for i in newArray5:
	for x in i:
		for y in x:
		  print(y)

1
2
3
4
5
6
7
8
9
10
11
12


Concatenate and Stack

In [37]:
array6 = np.array([[1,2],[3,4]])
array7 = np.array([[5,6],[7,8]])

newArray6 = np.concatenate((array6,array7))
print(newArray6)

newArray7 = np.stack((array6,array7))
print(newArray7)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Splitting arrays

In [42]:
array8 = np.array([1,2,3,4,5,6,7,8])
newArray8 = np.array_split(array8,4)
print(newArray8)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


Searching Index of array

In [43]:
array9 = np.array([1,2,3,4,5,6,7,8])

idx = np.where(array9%2 == 0)
print(idx)

(array([1, 3, 5, 7], dtype=int64),)


Sorting arrays

In [51]:
array10 = np.array([4.55,63.6,864,7,11,45])
print(np.sort(array10))

array11 = np.array(['banana', 'cherry', 'apple'])
print(np.sort(array11))


[  4.55   7.    11.    45.    63.6  864.  ]
['apple' 'banana' 'cherry']
